export default function studentData(){
  return [

    {
      id:1,
      firstName:"Jarrett",
      lastName:"Jaouen",
      email:"jjaouen0@noaa.gov",
      gender:"Male"
    },
    {
      id:2,
      firstName:"Anatol",
      lastName:"Lamzed",
      email:"alamzed1@hao123.com",
      gender:"Male"
    },
    {
      id:3,
      firstName:"Winna",
      lastName:"Casterot",
      email:"wcasterot2@chicagotribune.com",
      gender:"Female"
    },
    {
      id:4,
      firstName:"Ron",
      lastName:"Ratledge",
      email:"rratledge3@lulu.com",
      gender:"Female"
    },
    {
      id:5,
      firstName:"Conni",
      lastName:"RatledgeParks",
      email:"cparks4@fda.gov",
      gender:"Female"
    },


    {
      id:6,
      firstName:"Jarrett",
      lastName:"Jaouen",
      email:"jjaouen0@noaa.gov",
      gender:"Male"
    },
    {
      id:7,
      firstName:"Anatol",
      lastName:"Lamzed",
      email:"alamzed1@hao123.com",
      gender:"Male"
    },
    {
      id:8,
      firstName:"Winna",
      lastName:"Casterot",
      email:"wcasterot2@chicagotribune.com",
      gender:"Female"
    },
    {
      id:9,
      firstName:"Ron",
      lastName:"Ratledge",
      email:"rratledge3@lulu.com",
      gender:"Female"
    },
    {
      id:10,
      firstName:"Conni",
      lastName:"RatledgeParks",
      email:"cparks4@fda.gov",
      gender:"Female"
    },

    {
      id:11,
      firstName:"Jarrett",
      lastName:"Jaouen",
      email:"jjaouen0@noaa.gov",
      gender:"Male"
    },
    {
      id:12,
      firstName:"Anatol",
      lastName:"Lamzed",
      email:"alamzed1@hao123.com",
      gender:"Male"
    },
    {
      id:13,
      firstName:"Winna",
      lastName:"Casterot",
      email:"wcasterot2@chicagotribune.com",
      gender:"Female"
    },
    {
      id:14,
      firstName:"Ron",
      lastName:"Ratledge",
      email:"rratledge3@lulu.com",
      gender:"Female"
    },
    {
      id:15,
      firstName:"Conni",
      lastName:"RatledgeParks",
      email:"cparks4@fda.gov",
      gender:"Female"
    },

    {
      id:16,
      firstName:"Jarrett",
      lastName:"Jaouen",
      email:"jjaouen0@noaa.gov",
      gender:"Male"
    },
    {
      id:17,
      firstName:"Anatol",
      lastName:"Lamzed",
      email:"alamzed1@hao123.com",
      gender:"Male"
    },
    {
      id:18,
      firstName:"Winna",
      lastName:"Casterot",
      email:"wcasterot2@chicagotribune.com",
      gender:"Female"
    },
    {
      id:19,
      firstName:"Ron",
      lastName:"Ratledge",
      email:"rratledge3@lulu.com",
      gender:"Female"
    },
    {
      id:20,
      firstName:"Conni",
      lastName:"RatledgeParks",
      email:"cparks4@fda.gov",
      gender:"Female"
    }
  ]
}